### PR TITLE
Add element.contains method

### PR DESCRIPTION
**Pull request by bendrucker**

### CODE REVIEW

**Comment by mwiencek** [comment]
LGTM but might as well add it to the document prototype too?

```
> document.contains(document.body)
true
```

**Comment by bendrucker** [comment]
Right, good call! Added a ref to the document prototype as well as a corresponding test.

**Comment by mwiencek** [comment]
Awesome, looks identical to a patch I had in my fork but never got around to adding tests for. :+1:

**Comment by bendrucker** [comment]
Awesome! Lemme know when you have a chance to publish to npm.

**Comment by mwiencek** [comment]
You'll have to bug @Raynos for that :smile:

**Comment by bendrucker** [comment]
Can we throw in https://github.com/Raynos/value-event/pull/21 too ;)

**Pull request merged**
